Resources:
  SongsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-songs
      AttributeDefinitions:
        - AttributeName: songId
          AttributeType: S
        - AttributeName: artistId
          AttributeType: S
      KeySchema:
        - AttributeName: songId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        - IndexName: artist-songs-index
          KeySchema:
            - AttributeName: artistId
              KeyType: HASH
            - AttributeName: songId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}

        - IndexName: SongsArtistIndex
          KeySchema:
            - AttributeName: artistId
              KeyType: HASH
            - AttributeName: songId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}

  AlbumsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-albums
      AttributeDefinitions:
        - AttributeName: albumId
          AttributeType: S
        - AttributeName: artistId
          AttributeType: S
      KeySchema:
        - AttributeName: albumId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        - IndexName: AlbumsArtistIndex
          KeySchema:
            - AttributeName: artistId
              KeyType: HASH
            - AttributeName: albumId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: artist-albums-index
          KeySchema:
            - AttributeName: artistId
              KeyType: HASH
            - AttributeName: albumId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}

  ArtistsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-artists
      AttributeDefinitions:
        - AttributeName: artistId
          AttributeType: S
      KeySchema:
        - AttributeName: artistId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-users
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-main
      AttributeDefinitions:
        - AttributeName: partition
          AttributeType: S
        - AttributeName: sort
          AttributeType: S
        - AttributeName: lsi-1
          AttributeType: S
        - AttributeName: lsi-2
          AttributeType: S
        - AttributeName: lsi-3
          AttributeType: S
      KeySchema:
        - AttributeName: partition
          KeyType: HASH
        - AttributeName: sort
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: lsi-1
          KeySchema:
            - AttributeName: partition
              KeyType: HASH
            - AttributeName: lsi-1
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - sort
        - IndexName: lsi-2
          KeySchema:
            - AttributeName: partition
              KeyType: HASH
            - AttributeName: lsi-2
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - sort
        - IndexName: lsi-3
          KeySchema:
            - AttributeName: partition
              KeyType: HASH
            - AttributeName: lsi-3
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - sort
      GlobalSecondaryIndexes:
        - IndexName: gsi-1
          KeySchema:
            - AttributeName: sort
              KeyType: HASH
            - AttributeName: partition
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - title
              - published
              - type
