Resources:
  SongsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-songs
      AttributeDefinitions:
        - AttributeName: songId
          AttributeType: S
        - AttributeName: artistId
          AttributeType: S
      KeySchema:
        - AttributeName: songId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: SongsArtistIndex
          Projection:
            ProjectionType: KEYS_ONLY
          KeySchema:
            - AttributeName: artistId
              KeyType: HASH
            - AttributeName: songId
              KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  # AlbumsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: ${self:custom.stage}-albums
  #     AttributeDefinitions:
  #       - AttributeName: albumId
  #         AttributeType: S
  #       - AttributeName: artistId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: albumId
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: AlbumsArtistIndex
  #         Projection:
  #           ProjectionType: KEYS_ONLY
  #         KeySchema:
  #           - AttributeName: artistId
  #             KeyType: HASH
  #           - AttributeName: albumId
  #             KeyType: RANGE
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: ${self:custom.tableThroughput}
  #       WriteCapacityUnits: ${self:custom.tableThroughput}
  # ArtistsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: ${self:custom.stage}-artists
  #     AttributeDefinitions:
  #       - AttributeName: artistId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: artistId
  #         KeyType: HASH
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: ${self:custom.tableThroughput}
  #       WriteCapacityUnits: ${self:custom.tableThroughput}